

// TypeScript interfaces for search data
interface BaseSearchItem {
  id: string
  title: string
  titleAr: string
  url: string
  description: string
  descriptionAr: string
  keywords: string[]
  type: string
}




export interface PageItem extends BaseSearchItem {
  type: "page" | "program"
}

export interface NewsItem extends BaseSearchItem {
  type: "news"
  date: string
  category: string
  categoryAr: string
}

export interface EventItem extends BaseSearchItem {
  type: "event"
  date: string
  location: string
  locationAr: string
}

interface SearchData {
  pages: PageItem[]
  news: NewsItem[]
  events: EventItem[]
}

// Search data structure
export const searchData: SearchData = {
  pages: [
    {
      id: "home",
      title: "Home",
      titleAr: "الرئيسية",
      url: "/",
      description: "Welcome to Gezira College of Technology",
      descriptionAr: "مرحباً بكم في كلية الجزيرة للتكنولوجيا",
      keywords: [
        "home",
        "welcome",
        "college",
        "technology",
        "gezira",
        "main",
        "الرئيسية",
        "كلية",
        "تكنولوجيا",
        "الجزيرة",
      ],
      type: "page",
    },
    {
      id: "about",
      title: "About Us",
      titleAr: "حولنا",
      url: "/about",
      description: "Learn about our history, mission, and values",
      descriptionAr: "تعرف على تاريخنا ورسالتنا وقيمنا",
      keywords: ["about", "history", "mission", "values", "leadership", "حولنا", "تاريخ", "رسالة", "قيم", "قيادة"],
      type: "page",
    },
    {
      id: "academics",
      title: "Academic Programs",
      titleAr: "البرامج الأكاديمية",
      url: "/academics",
      description: "Explore our comprehensive academic programs",
      descriptionAr: "استكشف برامجنا الأكاديمية الشاملة",
      keywords: ["academics", "programs", "education", "degrees", "أكاديمي", "برامج", "تعليم", "درجات"],
      type: "page",
    },
    {
      id: "computer-science",
      title: "Computer Science",
      titleAr: "علوم الحاسوب",
      url: "/academics/computer-science",
      description: "Bachelor's degree in Computer Science with focus on AI and software development",
      descriptionAr: "درجة البكالوريوس في علوم الحاسوب مع التركيز على الذكاء الاصطناعي وتطوير البرمجيات",
      keywords: [
        "computer",
        "science",
        "programming",
        "AI",
        "software",
        "development",
        "حاسوب",
        "برمجة",
        "ذكاء اصطناعي",
        "تطوير",
      ],
      type: "program",
    },
    {
      id: "nursing",
      title: "Nursing Science",
      titleAr: "علوم التمريض",
      url: "/academics/nursing",
      description: "Bachelor's degree in Nursing Science for healthcare professionals",
      descriptionAr: "درجة البكالوريوس في علوم التمريض للمهنيين الصحيين",
      keywords: ["nursing", "healthcare", "medical", "patient care", "تمريض", "رعاية صحية", "طبي", "رعاية المرضى"],
      type: "program",
    },
    {
      id: "electrical-engineering",
      title: "Electrical Engineering",
      titleAr: "الهندسة الكهربائية",
      url: "/academics/electrical-engineering",
      description: "Bachelor's degree in Electrical and Electronic Engineering",
      descriptionAr: "درجة البكالوريوس في الهندسة الكهربائية والإلكترونية",
      keywords: [
        "electrical",
        "engineering",
        "electronics",
        "power",
        "systems",
        "هندسة كهربائية",
        "إلكترونيات",
        "طاقة",
        "أنظمة",
      ],
      type: "program",
    },
    {
      id: "architecture",
      title: "Architecture Engineering",
      titleAr: "هندسة العمارة",
      url: "/academics/architecture",
      description: "Bachelor's degree in Architecture Engineering and sustainable design",
      descriptionAr: "درجة البكالوريوس في هندسة العمارة والتصميم المستدام",
      keywords: [
        "architecture",
        "design",
        "building",
        "sustainable",
        "planning",
        "عمارة",
        "تصميم",
        "بناء",
        "مستدام",
        "تخطيط",
      ],
      type: "program",
    },
    {
      id: "business-administration",
      title: "Business Administration",
      titleAr: "إدارة الأعمال",
      url: "/academics/business-administration",
      description: "Bachelor's degree in Business Administration and management",
      descriptionAr: "درجة البكالوريوس في إدارة الأعمال والإدارة",
      keywords: [
        "business",
        "administration",
        "management",
        "finance",
        "marketing",
        "أعمال",
        "إدارة",
        "مالية",
        "تسويق",
      ],
      type: "program",
    },
    {
      id: "news",
      title: "News",
      titleAr: "الأخبار",
      url: "/news",
      description: "Latest news and announcements from the college",
      descriptionAr: "آخر الأخبار والإعلانات من الكلية",
      keywords: ["news", "announcements", "updates", "latest", "أخبار", "إعلانات", "تحديثات", "آخر"],
      type: "page",
    },
    {
      id: "events",
      title: "Events",
      titleAr: "الفعاليات",
      url: "/events",
      description: "Upcoming events, workshops, and conferences",
      descriptionAr: "الفعاليات القادمة وورش العمل والمؤتمرات",
      keywords: ["events", "workshops", "conferences", "activities", "فعاليات", "ورش عمل", "مؤتمرات", "أنشطة"],
      type: "page",
    },
    {
      id: "gallery",
      title: "Photo Gallery",
      titleAr: "معرض الصور",
      url: "/gallery",
      description: "Campus photos and university life",
      descriptionAr: "صور الحرم الجامعي والحياة الجامعية",
      keywords: ["gallery", "photos", "campus", "images", "معرض", "صور", "حرم جامعي", "صور"],
      type: "page",
    },
    {
      id: "contact",
      title: "Contact Us",
      titleAr: "اتصل بنا",
      url: "/contact",
      description: "Get in touch with us for inquiries and information",
      descriptionAr: "تواصل معنا للاستفسارات والمعلومات",
      keywords: ["contact", "phone", "email", "address", "location", "اتصال", "هاتف", "بريد", "عنوان", "موقع"],
      type: "page",
    },
    {
      id: "mba",
      title: "MBA - Master of Business Administration",
      titleAr: "ماجستير إدارة الأعمال",
      url: "/academics/mba",
      description: "Advanced business leadership and management program",
      descriptionAr: "برنامج متقدم في قيادة الأعمال والإدارة",
      keywords: [
        "MBA",
        "master",
        "business",
        "administration",
        "leadership",
        "management",
        "ماجستير",
        "إدارة",
        "أعمال",
        "قيادة",
      ],
      type: "program",
    },
    {
      id: "economic-sciences",
      title: "Economic Sciences",
      titleAr: "العلوم الاقتصادية",
      url: "/academics/economic-sciences",
      description: "Bachelor's degree in Economic Sciences and financial analysis",
      descriptionAr: "درجة البكالوريوس في العلوم الاقتصادية والتحليل المالي",
      keywords: [
        "economics",
        "economic",
        "sciences",
        "finance",
        "analysis",
        "اقتصاد",
        "علوم اقتصادية",
        "مالية",
        "تحليل",
      ],
      type: "program",
    },
    {
      id: "medical-laboratory",
      title: "Medical Laboratory Sciences",
      titleAr: "علوم المختبرات الطبية",
      url: "/academics/medical-laboratory",
      description: "Bachelor's degree in Medical Laboratory Sciences and diagnostics",
      descriptionAr: "درجة البكالوريوس في علوم المختبرات الطبية والتشخيص",
      keywords: [
        "medical",
        "laboratory",
        "sciences",
        "diagnostics",
        "clinical",
        "طبي",
        "مختبر",
        "علوم",
        "تشخيص",
        "سريري",
      ],
      type: "program",
    },
    {
      id: "medical-radiologic",
      title: "Medical Radiologic Technology",
      titleAr: "تقنية الأشعة الطبية",
      url: "/academics/medical-radiologic",
      description: "Bachelor's degree in Medical Radiologic Technology and imaging",
      descriptionAr: "درجة البكالوريوس في تقنية الأشعة الطبية والتصوير",
      keywords: [
        "medical",
        "radiologic",
        "technology",
        "imaging",
        "radiology",
        "طبي",
        "أشعة",
        "تقنية",
        "تصوير",
        "أشعة",
      ],
      type: "program",
    },
    {
      id: "public-health",
      title: "Public Health and Environmental Health",
      titleAr: "الصحة العامة والصحة البيئية",
      url: "/academics/public-health",
      description: "Bachelor's degree in Public Health and Environmental Health",
      descriptionAr: "درجة البكالوريوس في الصحة العامة والصحة البيئية",
      keywords: ["public", "health", "environmental", "community", "صحة عامة", "صحة بيئية", "مجتمع", "بيئة"],
      type: "program",
    },
    {
      id: "biomedical-engineering",
      title: "Biomedical Engineering",
      titleAr: "الهندسة الطبية الحيوية",
      url: "/academics/biomedical-engineering",
      description: "Bachelor's degree in Biomedical Engineering and medical devices",
      descriptionAr: "درجة البكالوريوس في الهندسة الطبية الحيوية والأجهزة الطبية",
      keywords: [
        "biomedical",
        "engineering",
        "medical",
        "devices",
        "biology",
        "هندسة طبية",
        "حيوية",
        "أجهزة طبية",
        "أحياء",
      ],
      type: "program",
    },
    {
      id: "information-technology",
      title: "Information Technology",
      titleAr: "تكنولوجيا المعلومات",
      url: "/academics/information-technology",
      description: "Bachelor's degree in Information Technology and systems",
      descriptionAr: "درجة البكالوريوس في تكنولوجيا المعلومات والأنظمة",
      keywords: ["information", "technology", "IT", "systems", "networks", "معلومات", "تكنولوجيا", "أنظمة", "شبكات"],
      type: "program",
    },
    {
      id: "english-literature",
      title: "English Language and Literature",
      titleAr: "اللغة الإنجليزية وآدابها",
      url: "/academics/english-literature",
      description: "Bachelor's degree in English Language and Literature",
      descriptionAr: "درجة البكالوريوس في اللغة الإنجليزية وآدابها",
      keywords: ["english", "language", "literature", "linguistics", "إنجليزية", "لغة", "أدب", "لسانيات"],
      type: "program",
    },
    {
      id: "physiotherapy",
      title: "Physiotherapy",
      titleAr: "العلاج الطبيعي",
      url: "/academics/physiotherapy",
      description: "Bachelor's degree in Physiotherapy and rehabilitation",
      descriptionAr: "درجة البكالوريوس في العلاج الطبيعي والتأهيل",
      keywords: ["physiotherapy", "physical", "therapy", "rehabilitation", "علاج طبيعي", "تأهيل", "علاج", "طبيعي"],
      type: "program",
    },
    // Additional comprehensive site content
    {
      id: "admissions",
      title: "Admissions",
      titleAr: "القبول",
      url: "/admissions",
      description: "Learn about our admission requirements and application process",
      descriptionAr: "تعرف على متطلبات القبول وعملية التقديم",
      keywords: ["admissions", "application", "requirements", "enrollment", "قبول", "تقديم", "متطلبات", "تسجيل"],
      type: "page",
    },
    {
      id: "student-life",
      title: "Student Life",
      titleAr: "الحياة الطلابية",
      url: "/student-life",
      description: "Discover campus life, clubs, activities and student services",
      descriptionAr: "اكتشف الحياة الجامعية والأندية والأنشطة والخدمات الطلابية",
      keywords: ["student", "life", "campus", "clubs", "activities", "services", "طلاب", "حياة", "أندية", "أنشطة", "خدمات"],
      type: "page",
    },
    {
      id: "faculty",
      title: "Faculty & Staff",
      titleAr: "هيئة التدريس والموظفين",
      url: "/faculty",
      description: "Meet our distinguished faculty members and academic staff",
      descriptionAr: "تعرف على أعضاء هيئة التدريس والكادر الأكاديمي المتميز",
      keywords: ["faculty", "staff", "professors", "teachers", "academic", "هيئة تدريس", "موظفين", "أساتذة", "معلمين", "أكاديمي"],
      type: "page",
    },
    {
      id: "research",
      title: "Research & Innovation",
      titleAr: "البحث والابتكار",
      url: "/research",
      description: "Explore our research centers, projects and innovation initiatives",
      descriptionAr: "استكشف مراكز البحث والمشاريع ومبادرات الابتكار",
      keywords: ["research", "innovation", "projects", "centers", "academic", "بحث", "ابتكار", "مشاريع", "مراكز", "أكاديمي"],
      type: "page",
    },
    {
      id: "library",
      title: "Library Services",
      titleAr: "خدمات المكتبة",
      url: "/library",
      description: "Access our digital and physical library resources and services",
      descriptionAr: "الوصول إلى مواردنا المكتبية الرقمية والمادية والخدمات",
      keywords: ["library", "books", "resources", "digital", "services", "مكتبة", "كتب", "موارد", "رقمي", "خدمات"],
      type: "page",
    },
    {
      id: "alumni",
      title: "Alumni Network",
      titleAr: "شبكة الخريجين",
      url: "/alumni",
      description: "Connect with our global alumni network and career opportunities",
      descriptionAr: "تواصل مع شبكة خريجينا العالمية والفرص المهنية",
      keywords: ["alumni", "graduates", "network", "career", "opportunities", "خريجين", "شبكة", "مهنة", "فرص"],
      type: "page",
    },
    {
      id: "international",
      title: "International Programs",
      titleAr: "البرامج الدولية",
      url: "/international",
      description: "Explore international partnerships, exchange programs and global opportunities",
      descriptionAr: "استكشف الشراكات الدولية وبرامج التبادل والفرص العالمية",
      keywords: ["international", "exchange", "global", "partnerships", "abroad", "دولي", "تبادل", "عالمي", "شراكات", "خارج"],
      type: "page",
    }
  ],
  news: [
    {
      id: "ai-lab",
      title: "New AI and Machine Learning Program Launched",
      titleAr: "إطلاق برنامج جديد للذكاء الاصطناعي والتعلم الآلي",
      url: "/news",
      description: "Cutting-edge program in AI and ML to meet growing demand",
      descriptionAr: "برنامج متطور في الذكاء الاصطناعي والتعلم الآلي لتلبية الطلب المتزايد",
      date: "2024-12-15",
      category: "Academic Programs",
      categoryAr: "البرامج الأكاديمية",
      keywords: ["AI", "machine learning", "program", "technology", "ذكاء اصطناعي", "تعلم آلي", "برنامج", "تكنولوجيا"],
      type: "news",
    },
    {
      id: "student-competition",
      title: "Student Research Team Wins National Competition",
      titleAr: "فريق بحث الطلاب يفوز بالمسابقة الوطنية",
      url: "/news",
      description: "Computer Science students win first place with healthcare app",
      descriptionAr: "طلاب علوم الحاسوب يفوزون بالمركز الأول بتطبيق الرعاية الصحية",
      date: "2024-12-10",
      category: "Student Achievement",
      categoryAr: "إنجاز الطلاب",
      keywords: [
        "students",
        "competition",
        "research",
        "healthcare",
        "app",
        "طلاب",
        "مسابقة",
        "بحث",
        "رعاية صحية",
        "تطبيق",
      ],
      type: "news",
    },
    {
      id: "international-partnership",
      title: "New Partnership with International Universities",
      titleAr: "شراكة جديدة مع الجامعات الدولية",
      url: "/news",
      description: "MOUs signed with leading universities for student exchange",
      descriptionAr: "توقيع مذكرات تفاهم مع جامعات رائدة لتبادل الطلاب",
      date: "2024-12-05",
      category: "Partnerships",
      categoryAr: "الشراكات",
      keywords: ["partnership", "international", "universities", "exchange", "شراكة", "دولي", "جامعات", "تبادل"],
      type: "news",
    },
    {
      id: "graduation-ceremony",
      title: "Graduation Ceremony 2025",
      titleAr: "حفل التخرج 2025",
      url: "/news",
      description: "Annual graduation ceremony celebrating our accomplished graduates",
      descriptionAr: "حفل التخرج السنوي للاحتفال بخريجينا المتميزين",
      date: "2025-06-15",
      category: "University Events",
      categoryAr: "فعاليات الجامعة",
      keywords: ["graduation", "ceremony", "graduates", "celebration", "تخرج", "حفل", "خريجين", "احتفال"],
      type: "news",
    },
    {
      id: "research-grant",
      title: "Major Research Grant Awarded",
      titleAr: "منحة بحثية كبرى ممنوحة",
      url: "/news",
      description: "University receives significant funding for healthcare innovation research",
      descriptionAr: "الجامعة تحصل على تمويل كبير لبحوث الابتكار في الرعاية الصحية",
      date: "2024-11-20",
      category: "Research",
      categoryAr: "البحث",
      keywords: ["research", "grant", "funding", "healthcare", "innovation", "بحث", "منحة", "تمويل", "رعاية صحية", "ابتكار"],
      type: "news",
    },
    {
      id: "new-campus",
      title: "New Campus Building Opens",
      titleAr: "افتتاح مبنى الحرم الجامعي الجديد",
      url: "/news",
      description: "State-of-the-art facilities enhance student learning experience",
      descriptionAr: "مرافق حديثة تعزز تجربة تعلم الطلاب",
      date: "2024-10-30",
      category: "Infrastructure",
      categoryAr: "البنية التحتية",
      keywords: ["campus", "building", "facilities", "infrastructure", "حرم جامعي", "مبنى", "مرافق", "بنية تحتية"],
      type: "news",
    }
  ],
  events: [
    {
      id: "science-fair",
      title: "Annual Science Fair 2025",
      titleAr: "معرض العلوم السنوي 2025",
      url: "/events",
      description: "Showcase of innovative student projects",
      descriptionAr: "عرض لمشاريع الطلاب المبتكرة",
      date: "2025-01-20",
      location: "Main Campus Auditorium",
      locationAr: "قاعة الحرم الجامعي الرئيسي",
      keywords: ["science", "fair", "projects", "innovation", "students", "علوم", "معرض", "مشاريع", "ابتكار", "طلاب"],
      type: "event",
    },
    {
      id: "career-workshop",
      title: "Career Development Workshop",
      titleAr: "ورشة تطوير المهن",
      url: "/events",
      description: "Professional development for final year students",
      descriptionAr: "التطوير المهني لطلاب السنة الأخيرة",
      date: "2025-01-25",
      location: "Conference Hall A",
      locationAr: "قاعة المؤتمرات أ",
      keywords: [
        "career",
        "workshop",
        "development",
        "professional",
        "students",
        "مهنة",
        "ورشة",
        "تطوير",
        "مهني",
        "طلاب",
      ],
      type: "event",
    },
    {
      id: "tech-symposium",
      title: "Technology Innovation Symposium",
      titleAr: "ندوة الابتكار التقني",
      url: "/events",
      description: "Annual symposium featuring latest technology trends and innovations",
      descriptionAr: "ندوة سنوية تعرض أحدث الاتجاهات والابتكارات التقنية",
      date: "2025-02-15",
      location: "Technology Center",
      locationAr: "مركز التكنولوجيا",
      keywords: ["technology", "innovation", "symposium", "trends", "tech", "تكنولوجيا", "ابتكار", "ندوة", "اتجاهات", "تقني"],
      type: "event",
    },
    {
      id: "health-conference",
      title: "Healthcare Excellence Conference",
      titleAr: "مؤتمر التميز في الرعاية الصحية",
      url: "/events",
      description: "International conference on healthcare innovations and best practices",
      descriptionAr: "مؤتمر دولي حول ابتكارات الرعاية الصحية وأفضل الممارسات",
      date: "2025-03-10",
      location: "Medical Complex",
      locationAr: "المجمع الطبي",
      keywords: ["healthcare", "medical", "conference", "excellence", "innovation", "رعاية صحية", "طبي", "مؤتمر", "تميز", "ابتكار"],
      type: "event",
    },
    {
      id: "job-fair",
      title: "Annual Job Fair",
      titleAr: "معرض الوظائف السنوي",
      url: "/events",
      description: "Connect with top employers and explore career opportunities",
      descriptionAr: "تواصل مع كبار أصحاب العمل واستكشف الفرص المهنية",
      date: "2025-04-05",
      location: "Exhibition Hall",
      locationAr: "قاعة المعارض",
      keywords: ["job", "fair", "employment", "career", "employers", "وظائف", "معرض", "توظيف", "مهنة", "أصحاب عمل"],
      type: "event",
    },
  ],
}